import { CheckCircle2, Edit3, Plus, Trash2 } from 'lucide-react'
import { FormEvent, useMemo, useState } from 'react'
import { Button, Card, Confirm, Empty, Field, FormActions, Loading, Modal, SearchInput, Segmented, Status } from '../../components/ui'
import { useAsync } from '../../hooks/useAsync'
import { brDate, brl, currentCompetence, toCents, today } from '../../utils/format'

const emptyForm = { tipo:'pagar', empresa_id:'', obra_id:'', categoria_id:'', descricao:'', competencia:currentCompetence(), emissao:today(), vencimento:today(), valor:'', forma_pagamento:'PIX', status:'pendente', observacoes:'' }

export default function FinancePage() {
  const [type, setType] = useState('pagar')
  const [search, setSearch] = useState('')
  const [competencia, setCompetencia] = useState(currentCompetence())
  const [form, setForm] = useState<any>(emptyForm)
  const [modal, setModal] = useState(false)
  const [payment, setPayment] = useState<any>(null)
  const [remove, setRemove] = useState<any>(null)
  const [saving, setSaving] = useState(false)
  const accounts = useAsync(() => window.fluxoDre.contas.list({tipo:type, competencia}), [type, competencia])
  const companies = useAsync(() => window.fluxoDre.empresas.list(), [])
  const categories = useAsync(() => window.fluxoDre.categorias.list({natureza:type === 'pagar' ? 'despesa' : 'receita'}), [type])
  const works = useAsync(() => window.fluxoDre.obras.list(), [])
  const rows = useMemo(() => accounts.data?.filter((row:any) => row.descricao.toLowerCase().includes(search.toLowerCase())) || [], [accounts.data, search])
  const total = rows.reduce((sum:any, row:any) => sum + row.valor_centavos, 0)
  const pending = rows.filter((row:any) => /pendente|vencido|parcial/.test(row.status)).length
  const settled = rows.filter((row:any) => /pago|recebido/.test(row.status)).length
  const overdue = rows.filter((row:any) => row.status === 'vencido')
  const overdueTotal = overdue.reduce((sum:number, row:any) => sum + row.valor_centavos, 0)

  const openForm = (row?:any) => { setForm(row ? {...row, valor:(row.valor_centavos / 100).toFixed(2).replace('.', ',')} : {...emptyForm, tipo:type, competencia}); setModal(true) }
  const submit = async (event:FormEvent) => { event.preventDefault(); setSaving(true); try { await window.fluxoDre.contas.save({...form, empresa_id:Number(form.empresa_id), obra_id:form.obra_id ? Number(form.obra_id) : null, categoria_id:form.categoria_id ? Number(form.categoria_id) : null, valor_centavos:toCents(form.valor), valor_bruto_centavos:toCents(form.valor)}); setModal(false); await accounts.reload() } finally { setSaving(false) } }
  const doPayment = async (event:FormEvent) => { event.preventDefault(); setSaving(true); try { await window.fluxoDre.contas.payment(payment.id, {valor_centavos:toCents(payment.paymentValue), data:payment.paymentDate, forma_pagamento:payment.forma_pagamento}); setPayment(null); await accounts.reload() } finally { setSaving(false) } }

  return <>
    <header className="command-header"><div><span className="command-eyebrow">Controle financeiro</span><h1>Contas</h1><p>Contas a pagar e receber com competencia, vencimento e baixas parciais.</p></div><div className="command-header-actions"><Button icon={<Plus size={16}/>} onClick={() => openForm()}>Nova conta</Button></div></header>
    <div className="command-filter-band command-finance-toolbar"><div className="toolbar-left"><Segmented value={type} onChange={setType} options={[{value:'pagar',label:'A pagar'},{value:'receber',label:'A receber'}]}/><SearchInput value={search} onChange={setSearch} placeholder="Buscar descricao..."/></div><Field label="Competencia"><input type="month" value={competencia} onChange={(event) => setCompetencia(event.target.value)}/></Field></div>
    <Card className="command-panel finance-command-panel"><div className="command-summary-strip"><div className={type === 'pagar' ? 'negative' : 'positive'}><span>Total no periodo</span><strong>{brl(total)}</strong></div><div><span>Pendentes</span><strong>{pending}</strong></div><div className="positive"><span>Liquidadas</span><strong>{settled}</strong></div><div className={overdue.length ? 'warning' : ''}><span>Exposicao vencida</span><strong>{brl(overdueTotal)}</strong><small>{overdue.length} registro(s)</small></div></div>
      {accounts.loading ? <Loading/> : rows.length ? <div className="table-wrap command-table-wrap"><table className="data-table command-data-table"><thead><tr><th>Detalhamento do lancamento</th><th>Categoria</th><th>Vencimento</th><th>Status</th><th className="number">Valor</th><th aria-label="Acoes"></th></tr></thead><tbody>{rows.map((row:any) => <tr className={row.status === 'vencido' ? 'row-overdue' : ''} key={row.id}><td><strong>{row.descricao}</strong><small>Competencia {row.competencia}</small></td><td>{categories.data?.find((category:any) => category.id === row.categoria_id)?.nome || '-'}</td><td>{brDate(row.vencimento)}</td><td><Status value={row.status}/></td><td className={`number ${type === 'pagar' ? 'amount-negative' : 'amount-positive'}`}>{brl(row.valor_centavos)}</td><td><div className="row-actions">{/pendente|vencido|parcial/.test(row.status) && <button className="icon-button" title="Registrar baixa" onClick={() => setPayment({...row, paymentValue:(row.valor_centavos / 100).toFixed(2).replace('.', ','), paymentDate:today()})}><CheckCircle2 size={16}/></button>}<button className="icon-button" onClick={() => openForm(row)} title="Editar"><Edit3 size={16}/></button><button className="icon-button danger-icon" onClick={() => setRemove(row)} title="Excluir"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div> : <Empty title="Sem contas nesta competencia" description="Registre uma conta ou importe uma planilha."/>}
    </Card>

    <Modal open={modal} title={form.id ? 'Editar conta' : 'Nova conta'} onClose={() => setModal(false)} size="lg"><form onSubmit={submit}><div className="modal-body form-grid form-grid-3"><Field label="Descricao" required wide><input required value={form.descricao} onChange={(event) => setForm({...form, descricao:event.target.value})}/></Field><Field label="Empresa" required><select required value={form.empresa_id} onChange={(event) => setForm({...form, empresa_id:event.target.value})}><option value="">Selecione</option>{companies.data?.map((company:any) => <option key={company.id} value={company.id}>{company.nome_fantasia || company.razao_social}</option>)}</select></Field><Field label="Obra"><select value={form.obra_id || ''} onChange={(event) => setForm({...form, obra_id:event.target.value})}><option value="">Sem obra</option>{works.data?.map((work:any) => <option key={work.id} value={work.id}>{work.nome}</option>)}</select></Field><Field label="Categoria"><select value={form.categoria_id || ''} onChange={(event) => setForm({...form, categoria_id:event.target.value})}><option value="">Sem categoria</option>{categories.data?.map((category:any) => <option key={category.id} value={category.id}>{category.nome}</option>)}</select></Field><Field label="Competencia" required><input required type="month" value={form.competencia} onChange={(event) => setForm({...form, competencia:event.target.value})}/></Field><Field label="Emissao"><input type="date" value={form.emissao || ''} onChange={(event) => setForm({...form, emissao:event.target.value})}/></Field><Field label="Vencimento" required><input required type="date" value={form.vencimento} onChange={(event) => setForm({...form, vencimento:event.target.value})}/></Field><Field label="Valor" required><input required inputMode="decimal" value={form.valor} onChange={(event) => setForm({...form, valor:event.target.value})} placeholder="0,00"/></Field><Field label="Forma de pagamento"><select value={form.forma_pagamento || ''} onChange={(event) => setForm({...form, forma_pagamento:event.target.value})}><option>PIX</option><option>Boleto</option><option>Transferencia</option><option>Dinheiro</option><option>Cartao</option></select></Field><Field label="Status"><select value={form.status} onChange={(event) => setForm({...form, status:event.target.value})}><option value="pendente">Pendente</option><option value="vencido">Vencido</option><option value="cancelado">Cancelado</option></select></Field><Field label="Observacoes" wide><textarea value={form.observacoes || ''} onChange={(event) => setForm({...form, observacoes:event.target.value})}/></Field></div><FormActions loading={saving} onCancel={() => setModal(false)}/></form></Modal>
    <Modal open={!!payment} title="Registrar pagamento/recebimento" onClose={() => setPayment(null)} size="sm">{payment && <form onSubmit={doPayment}><div className="modal-body form-grid"><Field label="Valor" required><input required value={payment.paymentValue} onChange={(event) => setPayment({...payment, paymentValue:event.target.value})}/></Field><Field label="Data" required><input required type="date" value={payment.paymentDate} onChange={(event) => setPayment({...payment, paymentDate:event.target.value})}/></Field><Field label="Forma"><select value={payment.forma_pagamento || 'PIX'} onChange={(event) => setPayment({...payment, forma_pagamento:event.target.value})}><option>PIX</option><option>Boleto</option><option>Transferencia</option><option>Dinheiro</option></select></Field></div><FormActions loading={saving} onCancel={() => setPayment(null)} submitLabel="Confirmar baixa"/></form>}</Modal>
    <Confirm open={!!remove} title="Excluir conta" description="O lancamento sera removido logicamente e deixara de aparecer nos relatorios." danger onCancel={() => setRemove(null)} onConfirm={async () => { await window.fluxoDre.contas.remove(remove.id); setRemove(null); accounts.reload() }}/>
  </>
}
