import { Edit3, Plus, Trash2 } from 'lucide-react'
import { FormEvent, useMemo, useState } from 'react'
import { Button, Card, Confirm, Empty, Field, FormActions, Loading, Modal, PageHeader } from '../components/ui'
import { useAsync } from '../hooks/useAsync'
import { brl, toCents } from '../utils/format'

const blank = { obra_id: '', frente_id: '', etapa_id: '', codigo: '', descricao: '', unidade: 'un', quantidade: '1', valor_unitario: '', tipo: 'material', observacoes: '' }

export default function BudgetPage() {
  const [work, setWork] = useState(''); const [form, setForm] = useState<any>(null); const [remove, setRemove] = useState<any>(null)
  const works = useAsync(() => window.fluxoDre.obras.list(), [])
  const fronts = useAsync(() => work ? window.fluxoDre.frentes.list({ obra_id: Number(work) }) : Promise.resolve([]), [work])
  const stages = useAsync(() => work ? window.fluxoDre.etapas.list({ obra_id: Number(work) }) : Promise.resolve([]), [work])
  const items = useAsync(() => work ? window.fluxoDre.orcamentos.list({ obra_id: Number(work) }) : Promise.resolve([]), [work])
  const total = useMemo(() => items.data?.reduce((sum: number, item: any) => sum + Math.round(Number(item.quantidade) * Number(item.valor_unitario_centavos)), 0) || 0, [items.data])
  const open = (item?: any) => setForm(item ? { ...item, valor_unitario: (item.valor_unitario_centavos / 100).toFixed(2).replace('.', ',') } : { ...blank, obra_id: work })
  async function submit(event: FormEvent) { event.preventDefault(); await window.fluxoDre.orcamentos.save({ ...form, obra_id: Number(form.obra_id), frente_id: form.frente_id ? Number(form.frente_id) : null, etapa_id: form.etapa_id ? Number(form.etapa_id) : null, quantidade: Number(form.quantidade), valor_unitario_centavos: toCents(form.valor_unitario), atualizado_em: new Date().toISOString() }); setForm(null); setWork(String(form.obra_id)); items.reload() }
  return <>
    <PageHeader title="Orçamento detalhado" description="Planeje materiais, serviços, equipes e equipamentos por frente de serviço." actions={<Button icon={<Plus size={16}/>} disabled={!work} onClick={() => open()}>Novo item</Button>}/>
    <div className="toolbar"><Field label="Obra"><select value={work} onChange={(event) => setWork(event.target.value)}><option value="">Selecione uma obra</option>{works.data?.map((item: any) => <option value={item.id} key={item.id}>{item.nome}</option>)}</select></Field><Card className="kpi" style={{ minHeight: 60, padding: '10px 15px' } as any}><div><span>Total orçado</span><strong>{brl(total)}</strong></div></Card></div>
    <Card>{items.loading ? <Loading/> : items.data?.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Item</th><th>Frente</th><th>Etapa</th><th>Tipo</th><th className="number">Total</th><th/></tr></thead><tbody>{items.data.map((item: any) => <tr key={item.id}><td><strong>{item.descricao}</strong><small>{item.codigo || item.unidade}</small></td><td>{fronts.data?.find((front: any) => front.id === item.frente_id)?.nome || 'Não classificada'}</td><td>{stages.data?.find((stage: any) => stage.id === item.etapa_id)?.nome || '—'}</td><td>{item.tipo.replaceAll('_', ' ')}</td><td className="number">{brl(Math.round(item.quantidade * item.valor_unitario_centavos))}</td><td><div className="row-actions"><button className="icon-button" onClick={() => open(item)}><Edit3 size={15}/></button><button className="icon-button" onClick={() => setRemove(item)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div> : <Empty title={work ? 'Orçamento vazio' : 'Selecione uma obra'} description="Cadastre os itens e classifique-os pela frente responsável."/>}</Card>
    <Modal open={!!form} title={form?.id ? 'Editar item' : 'Novo item orçamentário'} onClose={() => setForm(null)} size="lg"><form onSubmit={submit}><div className="modal-body form-grid form-grid-3"><Field label="Obra" required><select required value={form?.obra_id || ''} onChange={(event) => setForm({ ...form, obra_id: event.target.value, frente_id: '', etapa_id: '' })}><option value="">Selecione</option>{works.data?.map((item: any) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></Field><Field label="Frente"><select value={form?.frente_id || ''} onChange={(event) => setForm({ ...form, frente_id: event.target.value })}><option value="">Não classificada</option>{fronts.data?.map((item: any) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></Field><Field label="Etapa"><select value={form?.etapa_id || ''} onChange={(event) => setForm({ ...form, etapa_id: event.target.value })}><option value="">Sem etapa</option>{stages.data?.map((item: any) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></Field><Field label="Descrição" wide required><input required value={form?.descricao || ''} onChange={(event) => setForm({ ...form, descricao: event.target.value })}/></Field><Field label="Tipo"><select value={form?.tipo || 'material'} onChange={(event) => setForm({ ...form, tipo: event.target.value })}><option value="material">Material</option><option value="mao_de_obra">Mão de obra</option><option value="equipamento">Equipamento</option><option value="servico">Serviço</option></select></Field><Field label="Código"><input value={form?.codigo || ''} onChange={(event) => setForm({ ...form, codigo: event.target.value })}/></Field><Field label="Unidade"><input required value={form?.unidade || ''} onChange={(event) => setForm({ ...form, unidade: event.target.value })}/></Field><Field label="Quantidade"><input required type="number" step="0.001" min="0" value={form?.quantidade || ''} onChange={(event) => setForm({ ...form, quantidade: event.target.value })}/></Field><Field label="Valor unitário"><input required value={form?.valor_unitario || ''} onChange={(event) => setForm({ ...form, valor_unitario: event.target.value })}/></Field><Field label="Observações" wide><textarea value={form?.observacoes || ''} onChange={(event) => setForm({ ...form, observacoes: event.target.value })}/></Field></div><FormActions onCancel={() => setForm(null)}/></form></Modal>
    <Confirm open={!!remove} title="Excluir item" description="O item será removido do orçamento." danger onCancel={() => setRemove(null)} onConfirm={async () => { await window.fluxoDre.orcamentos.remove(remove.id); setRemove(null); items.reload() }}/>
  </>
}
