import { ArrowLeft, ArrowRight, CheckCircle2, FileSignature, FolderOpen, Printer, Save } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Button, Card, Field, Loading, PageHeader } from '../components/ui'
import { useAsync } from '../hooks/useAsync'
import { brl, toCents, today } from '../utils/format'

const steps=['Dados pessoais','Documentos e endereço','Contrato','Benefícios e EPI','Gerar documentos']
const docs=[['carta_sindical','Carta de oposição sindical'],['contrato_experiencia','Contrato de experiência'],['ficha_registro','Ficha de registro'],['livro_registro','Folha do livro de registro'],['ordem_servico','Ordem de serviço'],['vale_transporte','Vale-transporte'],['ficha_epi','Ficha de EPI']]
const initial:any={nome:'',cpf:'',rg:'',rg_emissao:'',rg_orgao:'SSP/SP',data_nascimento:'',naturalidade:'',nacionalidade:'Brasileira',estado_civil:'',sexo:'',escolaridade:'',pai:'',mae:'',ctps:'',ctps_serie:'',pis:'',cnh:'',titulo_eleitor:'',certificado_reservista:'',telefone:'',email:'',endereco:'',cep:'',empresa_id:'',obra_atual_id:'',cargo_id:'',departamento:'Operacional',admissao:today(),salario:'',status:'ativo',banco:'',agencia:'',conta_bancaria:'',pix:'',matricula:'',jornada_inicio:'07:00',intervalo_inicio:'11:00',intervalo_fim:'12:00',jornada_fim:'17:00',experiencia_dias:45,experiencia_fim:'',vale_transporte_opcao:1,vale_transporte_detalhes:'',observacoes:'',selectedDocs:docs.filter(([key])=>key!=='carta_sindical').map(([key])=>key),selectedEpis:[]}

export default function EmployeeRegistrationPage(){
  const [params]=useSearchParams(),id=params.get('id')
  const [step,setStep]=useState(0),[form,setForm]=useState<any>(initial),[saving,setSaving]=useState(false),[result,setResult]=useState<any>(null),[message,setMessage]=useState('')
  const companies=useAsync(()=>window.fluxoDre.empresas.list(),[]),works=useAsync(()=>window.fluxoDre.obras.list(),[]),catalog=useAsync(()=>window.fluxoDre.catalogo.list(),[]),epis=useAsync(()=>window.fluxoDre.epis.list(),[])
  useEffect(()=>{if(id)window.fluxoDre.funcionarios.get(Number(id)).then(employee=>employee&&setForm({...initial,...employee,salario:(employee.salario_centavos/100).toFixed(2).replace('.',',')}))},[id])
  useEffect(()=>{if(form.admissao){const date=new Date(`${form.admissao}T12:00:00`);date.setDate(date.getDate()+Number(form.experiencia_dias||45)-1);setForm((current:any)=>({...current,experiencia_fim:date.toISOString().slice(0,10)}))}},[form.admissao,form.experiencia_dias])
  useEffect(()=>{if(epis.data?.length&&!form.selectedEpis.length)setForm((current:any)=>({...current,selectedEpis:epis.data!.map((item:any)=>item.id)}))},[epis.data])
  const set=(key:string,value:any)=>setForm((current:any)=>({...current,[key]:value}))
  const activeCargos=catalog.data?.cargos.filter((item:any)=>item.ativo) || []
  const chosenCargo=catalog.data?.cargos.find((item:any)=>item.id===Number(form.cargo_id))
  const chosenBenefits=(catalog.data?.links||[]).filter((link:any)=>link.cargo_id===chosenCargo?.id&&link.ativo).map((link:any)=>({...link,benefit:catalog.data.beneficios.find((item:any)=>item.id===link.beneficio_id)}))
  const chooseCargo=(value:string)=>{const cargo=activeCargos.find((item:any)=>item.id===Number(value));setForm((current:any)=>({...current,cargo_id:value,salario:cargo?(cargo.salario_base_centavos/100).toFixed(2).replace('.',','):''}))}
  const validateIdentity=()=>{const fullName=String(form.nome||'').trim().split(/\s+/).filter(Boolean).length>=2,cpfDigits=String(form.cpf||'').replace(/\D/g,'');if(!fullName)return'Informe o nome completo do colaborador.';if(cpfDigits.length!==11)return'Informe um CPF válido com 11 dígitos.';return''}
  const saveEmployee=async()=>{const identityError=validateIdentity();if(identityError)throw new Error(identityError);setSaving(true);try{const employee=await window.fluxoDre.funcionarios.save({...form,empresa_id:form.empresa_id?Number(form.empresa_id):null,obra_atual_id:form.obra_atual_id?Number(form.obra_atual_id):null,cargo_id:form.cargo_id?Number(form.cargo_id):null,salario_centavos:toCents(form.salario),vale_transporte_opcao:Number(form.vale_transporte_opcao)});setForm((current:any)=>({...current,id:employee.id}));return employee}finally{setSaving(false)}}
  const next=()=>{if(step===0){const identityError=validateIdentity();if(identityError)return setMessage(identityError)}if(step===2&&(!form.empresa_id||!form.cargo_id))return setMessage('Selecione empresa e cargo.');setMessage('');setStep(Math.min(4,step+1))}
  const generate=async()=>{setSaving(true);setMessage('');try{const employee=await saveEmployee();for(const epiId of form.selectedEpis)await window.fluxoDre.funcionarioEpis.save({funcionario_id:employee.id,epi_id:Number(epiId),data_entrega:form.admissao||today(),quantidade:1});setResult(await window.fluxoDre.documentos.generate({funcionario_id:employee.id,includeCarta:form.selectedDocs.includes('carta_sindical'),selected:form.selectedDocs}))}catch(error:any){setMessage(error.message)}finally{setSaving(false)}}

  const content=useMemo(()=>{
    if(step===0)return <><h3 className="section-title">Identificação do colaborador</h3><div className="form-grid form-grid-3"><Field label="Nome completo" required wide><input value={form.nome} onChange={event=>set('nome',event.target.value)}/></Field><Field label="CPF" required><input required value={form.cpf} onChange={event=>set('cpf',event.target.value)}/></Field><Field label="Nascimento"><input type="date" value={form.data_nascimento} onChange={event=>set('data_nascimento',event.target.value)}/></Field><Field label="Estado civil"><input value={form.estado_civil} onChange={event=>set('estado_civil',event.target.value)}/></Field><Field label="Naturalidade"><input value={form.naturalidade} onChange={event=>set('naturalidade',event.target.value)}/></Field><Field label="Nacionalidade"><input value={form.nacionalidade} onChange={event=>set('nacionalidade',event.target.value)}/></Field><Field label="Telefone"><input value={form.telefone} onChange={event=>set('telefone',event.target.value)}/></Field><Field label="E-mail"><input type="email" value={form.email} onChange={event=>set('email',event.target.value)}/></Field><Field label="Nome do pai"><input value={form.pai} onChange={event=>set('pai',event.target.value)}/></Field><Field label="Nome da mãe"><input value={form.mae} onChange={event=>set('mae',event.target.value)}/></Field></div></>
    if(step===1)return <><h3 className="section-title">Documentos e endereço residencial</h3><div className="form-grid form-grid-3"><Field label="RG"><input value={form.rg} onChange={event=>set('rg',event.target.value)}/></Field><Field label="Emissão RG"><input type="date" value={form.rg_emissao} onChange={event=>set('rg_emissao',event.target.value)}/></Field><Field label="Órgão emissor"><input value={form.rg_orgao} onChange={event=>set('rg_orgao',event.target.value)}/></Field><Field label="CTPS"><input value={form.ctps} onChange={event=>set('ctps',event.target.value)}/></Field><Field label="Série CTPS"><input value={form.ctps_serie} onChange={event=>set('ctps_serie',event.target.value)}/></Field><Field label="PIS"><input value={form.pis} onChange={event=>set('pis',event.target.value)}/></Field><Field label="CNH"><input value={form.cnh} onChange={event=>set('cnh',event.target.value)}/></Field><Field label="CEP"><input value={form.cep} onChange={event=>set('cep',event.target.value)}/></Field><Field label="Endereço" wide><input value={form.endereco} onChange={event=>set('endereco',event.target.value)}/></Field></div></>
    if(step===2)return <><h3 className="section-title">Vínculo, jornada e remuneração</h3><div className="form-grid form-grid-3"><Field label="Empresa" required><select value={form.empresa_id} onChange={event=>set('empresa_id',event.target.value)}><option value="">Selecione</option>{companies.data?.map((item:any)=><option value={item.id} key={item.id}>{item.nome_fantasia||item.razao_social}</option>)}</select></Field><Field label="Obra atual"><select value={form.obra_atual_id} onChange={event=>set('obra_atual_id',event.target.value)}><option value="">Sem obra</option>{works.data?.filter((item:any)=>!form.empresa_id||item.empresa_id===Number(form.empresa_id)).map((item:any)=><option value={item.id} key={item.id}>{item.nome}</option>)}</select></Field><Field label="Cargo" required><select value={form.cargo_id} onChange={event=>chooseCargo(event.target.value)}><option value="">Selecione</option>{activeCargos.map((item:any)=><option value={item.id} key={item.id}>{item.nome} · CBO {item.cbo||'—'}</option>)}</select></Field><Field label="Admissão"><input type="date" value={form.admissao} onChange={event=>set('admissao',event.target.value)}/></Field><Field label="Salário mensal" hint="Preenchido automaticamente pelo cargo"><input value={form.salario} readOnly className="input-locked"/></Field><Field label="Matrícula"><input value={form.matricula} onChange={event=>set('matricula',event.target.value)}/></Field><Field label="Experiência (dias)"><input type="number" min="1" max="90" value={form.experiencia_dias} onChange={event=>set('experiencia_dias',event.target.value)}/></Field><Field label="Término da experiência"><input type="date" value={form.experiencia_fim} onChange={event=>set('experiencia_fim',event.target.value)}/></Field><Field label="Departamento"><input value={form.departamento} onChange={event=>set('departamento',event.target.value)}/></Field><Field label="Entrada"><input type="time" value={form.jornada_inicio} onChange={event=>set('jornada_inicio',event.target.value)}/></Field><Field label="Início intervalo"><input type="time" value={form.intervalo_inicio} onChange={event=>set('intervalo_inicio',event.target.value)}/></Field><Field label="Fim intervalo"><input type="time" value={form.intervalo_fim} onChange={event=>set('intervalo_fim',event.target.value)}/></Field><Field label="Saída"><input type="time" value={form.jornada_fim} onChange={event=>set('jornada_fim',event.target.value)}/></Field></div>{chosenCargo&&<div className="role-preview"><div><strong>{chosenCargo.nome}</strong><span>Salário-base {brl(chosenCargo.salario_base_centavos)}</span></div>{chosenBenefits.map((link:any)=><span className="benefit-chip" key={link.id}>{link.benefit?.nome}: {brl(link.valor_centavos)}</span>)}</div>}</>
    if(step===3)return <><h3 className="section-title">Benefícios, pagamento e equipamentos</h3><div className="notice fixed-benefit-notice">Os benefícios abaixo são herdados de <b>{chosenCargo?.nome||'cargo não definido'}</b> e entrarão automaticamente na folha: {chosenBenefits.length?chosenBenefits.map((link:any)=>`${link.benefit?.nome} (${brl(link.valor_centavos)})`).join(', '):'nenhum benefício fixo'}.</div><div className="form-grid form-grid-3" style={{marginTop:16}}><Field label="Vale-transporte"><select value={form.vale_transporte_opcao} onChange={event=>set('vale_transporte_opcao',event.target.value)}><option value="1">Opta pelo benefício</option><option value="0">Não opta</option></select></Field><Field label="Banco"><input value={form.banco} onChange={event=>set('banco',event.target.value)}/></Field><Field label="Agência"><input value={form.agencia} onChange={event=>set('agencia',event.target.value)}/></Field><Field label="Conta"><input value={form.conta_bancaria} onChange={event=>set('conta_bancaria',event.target.value)}/></Field><Field label="Chave PIX"><input value={form.pix} onChange={event=>set('pix',event.target.value)}/></Field><Field label="Trajeto e tarifas" wide><textarea value={form.vale_transporte_detalhes} onChange={event=>set('vale_transporte_detalhes',event.target.value)}/></Field></div><h3 className="section-title" style={{marginTop:20}}>EPIs entregues na admissão</h3><div className="doc-grid">{epis.data?.map((item:any)=><label className="doc-option" key={item.id}><input type="checkbox" checked={form.selectedEpis.includes(item.id)} onChange={event=>set('selectedEpis',event.target.checked?[...form.selectedEpis,item.id]:form.selectedEpis.filter((epiId:number)=>epiId!==item.id))}/><span><b>{item.nome}</b><small style={{display:'block',color:'#7d8797'}}>C.A. {item.ca}</small></span></label>)}</div></>
    return result?<div className="state" style={{minHeight:430}}><CheckCircle2 style={{color:'#159a76'}}/><strong>Dossiê gerado com sucesso</strong><p>{result.generated.length} documentos individuais e um PDF consolidado foram gravados na pasta escolhida.</p><div style={{display:'flex',gap:8}}><Button variant="secondary" icon={<FolderOpen size={16}/>} onClick={()=>window.fluxoDre.documentos.openFolder()}>Abrir pasta</Button><Button icon={<Printer size={16}/>} onClick={()=>window.fluxoDre.documentos.open(result.dossier)}>Abrir dossiê</Button></div></div>:<><h3 className="section-title">Selecione os documentos para gerar</h3><div className="notice">eSocial e certificados NR06, NR12, NR18 e NR35 permanecem como documentos externos.</div><div className="doc-grid" style={{marginTop:13}}>{docs.map(([key,label])=><label className="doc-option" key={key}><input type="checkbox" checked={form.selectedDocs.includes(key)} onChange={event=>set('selectedDocs',event.target.checked?[...form.selectedDocs,key]:form.selectedDocs.filter((item:string)=>item!==key))}/><FileSignature size={17}/><span><b>{label}</b><small style={{display:'block',color:'#7d8797'}}>{key==='carta_sindical'?'Opcional':'Modelo fornecido'}</small></span></label>)}</div></>
  },[step,form,companies.data,works.data,catalog.data,epis.data,result])

  return <><PageHeader title={id?'Documentos do funcionário':'Registro funcionário'} description="Selecione o cargo para preencher automaticamente salário e benefícios fixos." actions={form.id&&<Button variant="secondary" icon={<Save size={16}/>} onClick={saveEmployee}>Salvar alterações</Button>}/><Card><div className="progress"><div style={{width:`${(step+1)/steps.length*100}%`}}/></div><div className="wizard"><aside className="wizard-steps">{steps.map((label,index)=><div key={label} className={`wizard-step ${index===step?'active':''}`}><b>{index+1}</b><span>{label}</span></div>)}</aside><section className="wizard-content"><div className="modal-body">{companies.loading||catalog.loading?<Loading/>:content}{message&&<div className="notice" style={{marginTop:14}}>{message}</div>}</div>{!result&&<div className="form-actions"><Button variant="secondary" icon={<ArrowLeft size={16}/>} disabled={step===0} onClick={()=>setStep(step-1)}>Voltar</Button>{step<4?<Button icon={<ArrowRight size={16}/>} onClick={next}>Continuar</Button>:<Button disabled={saving||!form.selectedDocs.length} icon={<Printer size={16}/>} onClick={generate}>{saving?'Gerando...':'Salvar e gerar PDFs'}</Button>}</div>}</section></div></Card></>
}
