import { CheckCircle2, FileSpreadsheet, ShieldCheck, UploadCloud } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Button, Card, Empty, Field, Loading, PageHeader, Segmented } from '../components/ui'
import { brl, competenceLabel } from '../utils/format'

const labels:any={financeiro:'Financeiro',obras:'Obras',orcamento:'Orcamento',funcionarios:'Funcionarios',compras:'Compras',contratos:'Contratos',aditivos:'Aditivos',medicoes:'Medicoes',ponto:'Ponto',documentos:'Documentos',estoque:'Estoque'}
export default function ImportPage(){
 const [mode,setMode]=useState('universal'),[preview,setPreview]=useState<any>(null),[result,setResult]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
 const [file,setFile]=useState<any>(null),[sheet,setSheet]=useState(''),[area,setArea]=useState('financeiro'),[mapping,setMapping]=useState<any>({})
 const legacyChoose=async()=>{setLoading(true);setError('');try{setPreview(await window.fluxoDre.importacoes.preview());setResult(null)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 const legacyCommit=async()=>{setLoading(true);setError('');try{setResult(await window.fluxoDre.importacoes.commit(preview.token));setPreview(null)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 const choose=async()=>{setLoading(true);setError('');try{const selected=await window.fluxoDre.importadorUniversal.choose();setFile(selected);setResult(null);if(selected){const first=selected.sheets[0];setSheet(first.name);setArea(first.area)}}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(!file||!sheet)return;setLoading(true);setError('');window.fluxoDre.importadorUniversal.preview(file.token,{sheet,area,mapping:{}}).then((data)=>setMapping(data.mapping)).catch((e)=>setError(e.message)).finally(()=>setLoading(false))},[file,sheet,area])
 const universalPreview=async()=>{if(!file)return;setLoading(true);setError('');try{setPreview(await window.fluxoDre.importadorUniversal.preview(file.token,{sheet,area,mapping}))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 const universalCommit=async()=>{setLoading(true);setError('');try{setResult(await window.fluxoDre.importadorUniversal.commit(file.token,{sheet,area,mapping}));setPreview(null);setFile(null)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 const universal=mode==='universal'
 return <><PageHeader title={universal?'Importador universal':'Importar planilha 2026'} description={universal?'Leia modelos diversos de Excel ou CSV, confirme o destino e importe com auditoria.':'Assistente auditável da planilha histórica com aba 2026.'} actions={<Button icon={<UploadCloud size={16}/>} onClick={universal?choose:legacyChoose}>Selecionar planilha</Button>}/><Segmented options={[{value:'universal',label:'Importador universal'},{value:'legado',label:'Modelo 2026'}]} value={mode} onChange={(value)=>{setMode(value);setPreview(null);setResult(null);setError('')}}/>{loading?<Card style={{marginTop:14}}><Loading label="Lendo e validando a planilha..."/></Card>:result?<Result result={result} universal={universal}/>:universal?file?<UniversalSetup file={file} sheet={sheet} area={area} mapping={mapping} setSheet={setSheet} setArea={setArea} setMapping={setMapping} onPreview={universalPreview}/>:<Card style={{marginTop:14}}><Empty title="Pronto para reconhecer sua planilha" description="Selecione Excel ou CSV. O sistema analisa abas e cabeçalhos antes de criar qualquer dado." action={<Button onClick={choose}>Selecionar arquivo</Button>}/></Card>:preview?<LegacyPreview preview={preview} commit={legacyCommit}/>:<Card style={{marginTop:14}}><Empty title="Pronto para importar o modelo 2026" description="O assistente legado continua disponível para a planilha de despesas atual." action={<Button onClick={legacyChoose}>Selecionar arquivo</Button>}/></Card>}{preview&&universal&&<UniversalPreview preview={preview} file={file} sheet={sheet} area={area} mapping={mapping} setMapping={setMapping} onCommit={universalCommit}/>} {error&&<div className="notice" style={{marginTop:12}}>{error}</div>}</>
}
function UniversalSetup({file,sheet,area,mapping,setSheet,setArea,setMapping,onPreview}:any){return <Card style={{marginTop:14}}><div className="card-header"><div><h2>{file.file}</h2><p>Escolha a aba e confirme o destino sugerido.</p></div><Button onClick={onPreview}>Gerar prévia</Button></div><div className="modal-body form-grid form-grid-3"><Field label="Aba"><select value={sheet} onChange={(e)=>setSheet(e.target.value)}>{file.sheets.map((item:any)=><option key={item.name} value={item.name}>{item.name} · {item.rows} linhas</option>)}</select></Field><Field label="Área de destino"><select value={area} onChange={(e)=>setArea(e.target.value)}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{String(label)}</option>)}</select></Field><Field label="Detecção"><div className="locked-value">{labels[file.sheets.find((item:any)=>item.name===sheet)?.area] || 'Sem sugestão'}</div></Field></div><div className="card-body"><div className="notice">A prévia usa o mapeamento sugerido. Você poderá ajustar cada coluna antes de confirmar.</div></div></Card>}
function UniversalPreview({preview,file,sheet,area,mapping,setMapping,onCommit}:any){return <><div className="kpi-grid" style={{gridTemplateColumns:'repeat(3,1fr)',marginTop:14}}><Card className="kpi"><FileSpreadsheet/><div><span>Destino</span><strong style={{fontSize:13}}>{preview.label}</strong></div></Card><Card className="kpi"><ShieldCheck/><div><span>Linhas encontradas</span><strong>{preview.total}</strong></div></Card><Card className="kpi"><div><span>Cadastros possíveis</span><strong>{preview.createMissing.length}</strong><small>{preview.createMissing.join(', ')||'Nenhum'}</small></div></Card></div><Card><div className="card-header"><h2>Mapeamento de colunas</h2><Button disabled={preview.missing.length>0} onClick={onCommit}>Confirmar importação</Button></div><div className="card-body"><div className="form-grid form-grid-3">{Object.keys(preview.mapping).map((field)=><Field key={field} label={field.replaceAll('_',' ')}><select value={mapping[field]||''} onChange={(e)=>setMapping({...mapping,[field]:e.target.value})}><option value="">Não importar</option>{file.sheets.find((item:any)=>item.name===sheet)?.headers.map((header:string)=><option key={header} value={header}>{header}</option>)}</select></Field>)}</div>{preview.missing.length>0&&<div className="notice" style={{marginTop:14}}>Campos obrigatórios sem mapeamento: {preview.missing.join(', ')}.</div>}</div><div className="table-wrap"><table className="data-table"><thead><tr>{Object.values(preview.mapping).filter(Boolean).slice(0,6).map((header:any)=><th key={header}>{header}</th>)}</tr></thead><tbody>{preview.rows.map((row:any,index:number)=><tr key={index}>{Object.values(preview.mapping).filter(Boolean).slice(0,6).map((header:any)=><td key={String(header)}>{String(row[header as string]??'')}</td>)}</tr>)}</tbody></table></div></Card></>}
function LegacyPreview({preview,commit}:any){return <><div className="kpi-grid" style={{gridTemplateColumns:'repeat(3,1fr)',marginTop:14}}><Card className="kpi"><FileSpreadsheet/><div><span>Arquivo</span><strong style={{fontSize:13}}>{preview.file}</strong></div></Card><Card className="kpi"><ShieldCheck/><div><span>Aba validada</span><strong>2026</strong><small>{preview.range}</small></div></Card><Card className="kpi"><div><span>Funcionários encontrados</span><strong>{preview.employees.length}</strong></div></Card></div><Card><div className="card-header"><h2>Prévia dos blocos mensais</h2><Button onClick={commit}>Confirmar importação</Button></div><div className="card-body"><div className="import-months">{preview.months.map((m:any)=><div className="import-month" key={m.competencia}><strong>{competenceLabel(m.competencia)}</strong><span>{m.funcionarios} funcionários · {m.despesas} despesas · {m.receitas} receitas</span></div>)}</div></div></Card></>}
function Result({result,universal}:any){if(universal)return <Card style={{marginTop:14}}><div className="state"><CheckCircle2 style={{color:'#159a76'}}/><strong>Importação concluída</strong><p>{result.imported} linhas de {labels[result.area]} foram processadas e {result.created} cadastros ausentes foram criados.</p></div></Card>;return <Card style={{marginTop:14}}><div className="state"><CheckCircle2 style={{color:'#159a76'}}/><strong>Importação concluída</strong><p>{result.imported} lançamentos e {result.employees} funcionários foram normalizados.</p></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Competência</th><th className="number">Receitas importadas</th><th className="number">Despesas importadas</th></tr></thead><tbody>{result.reconciliation.map((item:any)=><tr key={item.competencia}><td>{competenceLabel(item.competencia)}</td><td className="number">{brl(item.importado_receitas)}</td><td className="number">{brl(item.importado_despesas)}</td></tr>)}</tbody></table></div></Card>}
