import { Edit3, Plus, Trash2 } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Button, Card, Confirm, Empty, Field, FormActions, Loading, Modal, PageHeader, Segmented, Status } from '../components/ui'
import { useAsync } from '../hooks/useAsync'

const configs:any={empresas:{title:'Empresa',api:()=>window.fluxoDre.empresas,fields:['razao_social','nome_fantasia','cnpj','telefone','email','endereco','observacoes']},clientes:{title:'Cliente',api:()=>window.fluxoDre.clientes,fields:['nome','documento','telefone','email','observacoes']},fornecedores:{title:'Fornecedor',api:()=>window.fluxoDre.fornecedores,fields:['nome','documento','telefone','email','observacoes']}}
const labels:any={razao_social:'Razão social',nome_fantasia:'Nome fantasia',cnpj:'CNPJ',telefone:'Telefone',email:'E-mail',endereco:'Endereço',observacoes:'Observações',nome:'Nome',documento:'CPF/CNPJ'}
export default function RegistriesPage(){
 const [tab,setTab]=useState('empresas'),[form,setForm]=useState<any>(null),[remove,setRemove]=useState<any>(null),[version,setVersion]=useState(0),cfg=configs[tab]
 const data=useAsync<any[]>(()=>cfg.api().list(),[tab,version])
 const submit=async(e:FormEvent)=>{e.preventDefault();await cfg.api().save({...form,status:form.status||'ativa'});setForm(null);setVersion(x=>x+1)}
 return <><PageHeader title="Empresas e parceiros" description="Cadastros-base usados por obras, contas e documentos." actions={<Button icon={<Plus size={16}/>} onClick={()=>setForm({status:'ativa'})}>Novo {cfg.title.toLowerCase()}</Button>}/><div className="toolbar"><Segmented value={tab} onChange={setTab} options={[{value:'empresas',label:'Empresas'},{value:'clientes',label:'Clientes'},{value:'fornecedores',label:'Fornecedores'}]}/></div><Card>{data.loading?<Loading/>:data.data?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Nome</th><th>Documento</th><th>Contato</th>{tab==='empresas'&&<th>Status</th>}<th></th></tr></thead><tbody>{data.data.map((x:any)=><tr key={x.id}><td><strong>{x.nome_fantasia||x.razao_social||x.nome}</strong>{x.razao_social&&x.nome_fantasia&&<small style={{display:'block',color:'#8993a3'}}>{x.razao_social}</small>}</td><td>{x.cnpj||x.documento||'—'}</td><td>{x.email||x.telefone||'—'}</td>{tab==='empresas'&&<td><Status value={x.status}/></td>}<td><div className="row-actions"><button className="icon-button" onClick={()=>setForm(x)}><Edit3 size={15}/></button><button className="icon-button" onClick={()=>setRemove(x)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>:<Empty title={`Nenhum ${cfg.title.toLowerCase()} cadastrado`}/>}</Card><Modal open={!!form} title={`${form?.id?'Editar':'Novo'} ${cfg.title.toLowerCase()}`} onClose={()=>setForm(null)}><form onSubmit={submit}><div className="modal-body form-grid">{cfg.fields.map((field:string)=><Field key={field} label={labels[field]} wide={field==='endereco'||field==='observacoes'} required={field==='razao_social'||field==='nome'}>{field==='observacoes'?<textarea value={form?.[field]||''} onChange={(e)=>setForm({...form,[field]:e.target.value})}/>:<input required={field==='razao_social'||field==='nome'} type={field==='email'?'email':'text'} value={form?.[field]||''} onChange={(e)=>setForm({...form,[field]:e.target.value})}/>}</Field>)}</div><FormActions onCancel={()=>setForm(null)}/></form></Modal><Confirm open={!!remove} title={`Excluir ${cfg.title.toLowerCase()}`} description="O cadastro será removido logicamente e os vínculos existentes serão preservados quando aplicável." danger onCancel={()=>setRemove(null)} onConfirm={async()=>{await cfg.api().remove(remove.id);setRemove(null);setVersion(x=>x+1)}}/></>
}
