import { Edit3, Plus, Trash2 } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Button, Card, Confirm, Empty, Field, FormActions, Loading, Modal, PageHeader, Status } from '../components/ui'
import { useAsync } from '../hooks/useAsync'
import { brDate, brl, toCents } from '../utils/format'

const blank = { obra_id: '', frente_id: '', nome: '', responsavel: '', previsto_inicio: '', previsto_fim: '', percentual_previsto: '0', percentual_realizado: '0', custo_planejado: '0', custo_realizado: '0', status: 'pendente', observacoes: '' }

export default function SchedulePage() {
  const [work, setWork] = useState(new URLSearchParams(location.search).get('obra') || '')
  const [form, setForm] = useState<any>(null)
  const [remove, setRemove] = useState<any>(null)
  const works = useAsync(() => window.fluxoDre.obras.list(), [])
  const fronts = useAsync(() => work ? window.fluxoDre.frentes.list({ obra_id: Number(work) }) : Promise.resolve([]), [work])
  const items = useAsync(() => work ? window.fluxoDre.cronograma.list({ obra_id: Number(work) }) : Promise.resolve([]), [work])
  const overview = useAsync(() => work ? window.fluxoDre.planejamento.overview(Number(work)) : Promise.resolve(null), [work])
  const open = (item?: any) => setForm(item ? { ...item, frente_id: item.frente_id || '', percentual_previsto: String(item.percentual_previsto), percentual_realizado: String(item.percentual_realizado), custo_planejado: (item.custo_planejado_centavos / 100).toFixed(2).replace('.', ','), custo_realizado: (item.custo_realizado_centavos / 100).toFixed(2).replace('.', ',') } : { ...blank, obra_id: work })
  async function submit(event: FormEvent) {
    event.preventDefault()
    await window.fluxoDre.cronograma.save({ ...form, obra_id: Number(form.obra_id), frente_id: form.frente_id ? Number(form.frente_id) : null, percentual_previsto: Number(form.percentual_previsto), percentual_realizado: Number(form.percentual_realizado), custo_planejado_centavos: toCents(form.custo_planejado), custo_realizado_centavos: toCents(form.custo_realizado) })
    setWork(String(form.obra_id))
    setForm(null)
    items.reload()
    overview.reload()
  }
  const curveMax = Math.max(1, ...(overview.data?.curve || []).map((item: any) => Math.max(item.previsto_centavos, item.realizado_centavos)))
  return <>
    <PageHeader title="Planejamento fisico-financeiro" description="Planeje etapas por frente, Curva S, marcos e caixa previsto." actions={<Button icon={<Plus size={16}/>} disabled={!work} onClick={() => open()}>Nova etapa</Button>}/>
    <div className="filters"><Field label="Obra"><select value={work} onChange={(event) => setWork(event.target.value)}><option value="">Selecione</option>{works.data?.map((item: any) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></Field></div>
    {overview.data?.curve?.length ? <div className="dashboard-grid" style={{ marginBottom: 14 }}>
      <Card><div className="card-header"><h2>Curva S</h2><span>Previsto x realizado acumulado</span></div><div className="card-body stage-list">{overview.data.curve.map((item: any) => <div key={item.etapa_id}><div><strong>{item.nome}</strong><span>{brDate(item.data)}</span></div><div className="curve-bars"><span style={{ width: `${Math.max(4, item.previsto_centavos / curveMax * 100)}%` }}>{brl(item.previsto_centavos)}</span><span style={{ width: `${Math.max(4, item.realizado_centavos / curveMax * 100)}%` }}>{brl(item.realizado_centavos)}</span></div></div>)}</div></Card>
      <Card><div className="card-header"><h2>Previsao de caixa</h2><span>Receber x pagar por competencia</span></div>{overview.data.cash?.length ? <div className="stage-list">{overview.data.cash.map((item: any) => <div key={item.competencia}><div><strong>{item.competencia}</strong><span>Receber {brl(item.receber_centavos)} / pagar {brl(item.pagar_centavos)}</span></div><div className="number">{brl(item.saldo_acumulado_centavos)}</div></div>)}</div> : <Empty title="Sem contas vinculadas" description="Contas da obra alimentam a previsao automaticamente."/>}</Card>
    </div> : null}
    <Card>{items.loading ? <Loading/> : items.data?.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Etapa</th><th>Frente</th><th>Prazo</th><th>Status</th><th>Avanco</th><th className="number">Custo planejado</th><th/></tr></thead><tbody>{items.data.map((item: any) => <tr key={item.id}><td><strong>{item.nome}</strong><small>{item.responsavel}</small></td><td>{fronts.data?.find((front: any) => front.id === item.frente_id)?.nome || 'Obra geral'}</td><td>{brDate(item.previsto_inicio)} a {brDate(item.previsto_fim)}</td><td><Status value={item.status}/></td><td>{item.percentual_previsto}% / {item.percentual_realizado}%</td><td className="number">{brl(item.custo_planejado_centavos)}</td><td><button className="icon-button" onClick={() => open(item)}><Edit3 size={15}/></button><button className="icon-button" onClick={() => setRemove(item)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div> : <Empty title={work ? 'Nenhuma etapa planejada' : 'Selecione uma obra'} description="Cadastre etapas e associe cada uma a uma frente."/>}</Card>
    <Modal open={!!form} title="Etapa do cronograma" onClose={() => setForm(null)} size="lg"><form onSubmit={submit}><div className="modal-body form-grid form-grid-3"><Field label="Obra" required><select required value={form?.obra_id || ''} onChange={(event) => { setWork(event.target.value); setForm({ ...form, obra_id: event.target.value, frente_id: '' }) }}><option value="">Selecione</option>{works.data?.map((item: any) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></Field><Field label="Frente"><select value={form?.frente_id || ''} onChange={(event) => setForm({ ...form, frente_id: event.target.value })}><option value="">Obra geral</option>{fronts.data?.map((item: any) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></Field><Field label="Status"><select value={form?.status || 'pendente'} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="pendente">Pendente</option><option value="em_andamento">Em andamento</option><option value="concluida">Concluida</option><option value="atrasada">Atrasada</option></select></Field><Field label="Nome" wide required><input required value={form?.nome || ''} onChange={(event) => setForm({ ...form, nome: event.target.value })}/></Field><Field label="Responsavel"><input value={form?.responsavel || ''} onChange={(event) => setForm({ ...form, responsavel: event.target.value })}/></Field><Field label="Inicio"><input type="date" value={form?.previsto_inicio || ''} onChange={(event) => setForm({ ...form, previsto_inicio: event.target.value })}/></Field><Field label="Fim"><input type="date" value={form?.previsto_fim || ''} onChange={(event) => setForm({ ...form, previsto_fim: event.target.value })}/></Field><Field label="% previsto"><input type="number" min="0" max="100" value={form?.percentual_previsto || 0} onChange={(event) => setForm({ ...form, percentual_previsto: event.target.value })}/></Field><Field label="% realizado"><input type="number" min="0" max="100" value={form?.percentual_realizado || 0} onChange={(event) => setForm({ ...form, percentual_realizado: event.target.value })}/></Field><Field label="Custo planejado"><input value={form?.custo_planejado || ''} onChange={(event) => setForm({ ...form, custo_planejado: event.target.value })}/></Field><Field label="Custo realizado"><input value={form?.custo_realizado || ''} onChange={(event) => setForm({ ...form, custo_realizado: event.target.value })}/></Field></div><FormActions onCancel={() => setForm(null)}/></form></Modal>
    <Confirm open={!!remove} title="Excluir etapa" description="A etapa sera removida do cronograma." danger onCancel={() => setRemove(null)} onConfirm={async () => { await window.fluxoDre.cronograma.remove(remove.id); setRemove(null); items.reload(); overview.reload() }}/>
  </>
}
