const { esc,dateBR,money,time,companyName,companyAddress,page } = require('./common.cjs')

function contractTemplate({ employee, company }) {
  const employer=companyName(company), addr=companyAddress(company), role=employee.cargo_nome||''
  const start=time(employee.jornada_inicio,'07:00'), i1=time(employee.intervalo_inicio,'11:00'), i2=time(employee.intervalo_fim,'12:00'), end=time(employee.jornada_fim,'17:00')
  const header=`<div class="small">Ribeirão Preto<br>SP<br>${esc(company?.cep||'14027-005')}<br><b>${esc(employer)}</b><br>${esc(addr)}<br>CNPJ: ${esc(company?.cnpj||'')}</div>`
  const p1=`${header}<p>Entre a Empresa <b>${esc(employer)}</b>, com sede em ${esc(addr)}, doravante designada simplesmente EMPREGADORA, e <b>${esc(employee.nome)}</b>, portador da Carteira de Trabalho número ${esc(employee.ctps||'')} Série ${esc(employee.ctps_serie||'')}${employee.ctps_uf?'-'+esc(employee.ctps_uf):''}, a seguir chamado EMPREGADO, é celebrado o presente CONTRATO DE EXPERIÊNCIA, que terá vigência a partir da data de início da prestação de serviços, de acordo com as condições a seguir estabelecidas:</p>
  <p>Fica o EMPREGADO admitido no quadro de funcionários da EMPREGADORA para exercer a função de <b>${esc(role)}</b>. Horário de Trabalho (Semana) das ${esc(start)} às ${esc(i1)} e das ${esc(i2)} às ${esc(end)}. Descanso: Domingo, mediante a remuneração de <b>${money(employee.salario_centavos)}</b>, por mês. A circunstância, porém, de ser a função especificada não importa na intransferibilidade do EMPREGADO para outro serviço, no qual demonstre melhor capacidade de adaptação desde que compatível com sua condição pessoal.</p>
  <p>O horário de trabalho será anotado na sua ficha de registro e a eventual redução de jornada por determinação da EMPREGADORA não inovará este ajuste, permanecendo sempre íntegra a obrigação do EMPREGADO de cumprir o horário que lhe for determinado, observando o limite legal.</p>
  <p>Obriga-se também o empregado a prestar serviços em horas extraordinárias, sempre que lhe for determinado pela EMPREGADORA, na forma prevista em Lei. Na hipótese desta faculdade pela EMPREGADORA, o EMPREGADO receberá as horas extraordinárias com o acréscimo legal, salvo a ocorrência de compensação, com a consequente redução de jornada de trabalho em outro dia.</p>
  <p>Aceita o EMPREGADO, expressamente, a condição de prestar serviços em quaisquer dos turnos de trabalho, isto é, tanto durante o dia como à noite, desde que sem simultaneidade, observadas as prescrições legais reguladoras do assunto quanto à remuneração.</p>
  <p>Fica ajustado, nos termos do parágrafo 1º do artigo 469 da Consolidação das Leis do Trabalho, que o EMPREGADO acatará a ordem emanada da EMPREGADORA para prestação de serviços tanto na localidade de celebração do Contrato como em outra localidade do mesmo município ou de outra cidade, quer a transferência seja transitória, quer definitiva.</p>
  <p>No ato da assinatura deste contrato, o EMPREGADO recebe o Regulamento Interno da Empresa, cujas cláusulas fazem parte do Contrato de Trabalho, e a violação de qualquer delas implicará sanção cuja graduação dependerá da gravidade, culminando com a rescisão do contrato.</p>
  <p>Em caso de dano causado pelo EMPREGADO, fica a EMPREGADORA autorizada a efetivar o desconto da importância correspondente ao prejuízo, com fundamento no parágrafo 1º do artigo 462 da Consolidação das Leis do Trabalho.</p>
  <p>O presente Contrato vigerá durante <b>${String(employee.experiencia_dias||45).padStart(3,'0')} dias</b>, com início em ${dateBR(employee.admissao)} e término em ${dateBR(employee.experiencia_fim)}, sendo celebrado para as partes verificarem reciprocamente a conveniência ou não de se vincular em caráter definitivo.</p>
  <div class="sig"><div>${esc(employer)}<br>EMPREGADORA</div><div>${esc(employee.nome)}<br>EMPREGADO</div></div><div class="page"></div>`
  const p2=`<p>Opera-se a rescisão do presente Contrato pela decorrência do prazo supra. Rescindindo-se por vontade do EMPREGADO ou pela EMPREGADORA com Justa Causa, nenhuma indenização é devida. Rescindindo-se antes do prazo, pela EMPREGADORA ou EMPREGADO, ficam as partes sujeitas ao disposto nos artigos 479 e 480 da C.L.T., sem prejuízo do disposto no Regulamento do F.G.T.S. Nenhum aviso prévio é devido pela rescisão do presente Contrato.</p>
  <p>Na hipótese deste ajuste transformar-se em Contrato de Prazo Indeterminado pelo decurso do tempo, continuarão em plena vigência as cláusulas anteriores enquanto durarem as relações do Empregado com a EMPREGADORA.</p>
  <p>E por estarem de pleno acordo, as partes contratantes assinam o presente contrato de experiência em duas vias, ficando a primeira em poder da EMPREGADORA e a segunda com o EMPREGADO.</p>
  <p class="center">Ribeirão Preto, ${dateBR(employee.admissao)}</p>
  <div class="sig"><div>TESTEMUNHA<br><br>RESPONSÁVEL<br><br>TESTEMUNHA</div><div>${esc(employer)}<br><br><br>${esc(employee.nome)}</div></div>
  <h2>PRORROGAÇÃO DO CONTRATO DE TRABALHO A TÍTULO DE EXPERIÊNCIA</h2><p>Por mútuo acordo entre as partes, fica o presente contrato de experiência que deveria vencer nesta data prorrogado até ____/____/________.</p><p>........................, ..... de .................... de .........</p><div class="sig"><div>TESTEMUNHA<br><br>RESPONSÁVEL<br><br>TESTEMUNHA</div><div>${esc(employer)}<br><br><br>${esc(employee.nome)}</div></div>`
  return page('CONTRATO DE TRABALHO A TÍTULO DE EXPERIÊNCIA', p1+p2)
}
module.exports={contractTemplate}
