const { esc,dateBR,companyName,page } = require('./common.cjs')
const DEFAULTS=[['Uniforme','-',3],['Botina','12160',1],['Capacete c/ jugular','36099',1],['Protetor auditivo','5745',1],['Protetor solar','-','PT'],['Touca árabe','-',1],['Luva Multitato','30916',1],['Óculos de proteção','9722',1],['Máscara PFF2','10578',1],['Cinto de Segurança c/ Talabarte e Trava Quedas','41046',1]]
const norm=(value)=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')
function withDefaultQuantity(item){const found=DEFAULTS.find(([nome,ca])=>norm(nome)===norm(item.nome)||String(ca)!=='-'&&String(ca)===String(item.ca));if(!found)return item;const standard=found[2];return {...item,quantidade:(item.quantidade!=null&&Number(item.quantidade)!==1)?item.quantidade:standard}}
function epiTemplate({employee,company,epis}){
 const items=(epis&&epis.length?epis.map(withDefaultQuantity):DEFAULTS.map(([nome,ca,quantidade])=>({nome,ca,quantidade,data_entrega:employee.admissao})))
 const rows=items.map(i=>`<tr><td>${dateBR(i.data_entrega||employee.admissao)}</td><td>${esc(i.nome||'')}</td><td>${esc(i.ca||'-')}</td><td>${esc(i.quantidade??'')}</td><td></td><td>${dateBR(i.data_devolucao)}</td><td>${esc(i.quantidade_devolvida??'')}</td></tr>`).join('')
 const body=`<p><b>Nome:</b> ${esc(employee.nome)} &nbsp;&nbsp;&nbsp; <b>Função:</b> ${esc(employee.cargo_nome||'')}</p><p><b>A.</b> Declaro haver recebido, para meu uso e proteção pessoal em serviço, os equipamentos de proteção individual abaixo descritos, comprometendo-me a utilizá-los de acordo com as orientações técnicas recebidas.</p><p><b>B.</b> Responsabilizo-me pela guarda e conservação dos referidos equipamentos, respondendo por desaparecimento e/ou danos causados por descuido ou mau uso.</p><p><b>C.</b> Comprometo-me a apresentar para troca todo equipamento que, no decorrer do uso, apresentar defeito ou desgaste natural, tão logo seja constatado.</p><p><b>D.</b> Declaro estar ciente de que o não uso dos equipamentos de proteção individual abaixo discriminados constitui ato faltoso, sujeito às medidas disciplinares aplicáveis.</p><div class="sig"><div>Assinatura do funcionário</div><div>${esc(companyName(company))}</div></div><h2>EQUIPAMENTOS RECEBIDOS</h2><table><tr><th>Data da entrega</th><th>Descrição</th><th>C.A.</th><th>Qtda.</th><th>Assinatura</th><th>Data da devolução</th><th>Qtda.</th></tr>${rows}</table>`
 return page('FICHA DE CONTROLE DE E.P.I.',body,'body{font-size:9pt}td{height:26px}')
}
module.exports={epiTemplate}
