const { esc,dateBR,money,time,employeeAddress,companyName,companyAddress,page } = require('./common.cjs')

function c(label,value,span=''){return `<div class="cell ${span}"><div class="label">${label}</div><div class="value">${esc(value||'')}</div></div>`}
function registrationTemplate({employee,company}){
 const employer=companyName(company), residence=employeeAddress(employee), cbo=employee.cbo||''
 const body=`<div class="grid">${c('Autenticar','')}${c('Matrícula eSocial',employee.matricula_esocial||employee.matricula)}${c('Nº',employee.matricula||employee.matricula_esocial)}${c('Empregador',employer)}${c('CNPJ',company?.cnpj)}${c('Endereço',companyAddress(company),'')}</div>
 <div class="grid">${c('Empregado',employee.nome)}${c('Beneficiários',employee.beneficiarios)}${c('Residência',residence)}${c('Data de nascimento',dateBR(employee.data_nascimento))}${c('Local do nascimento',employee.naturalidade)}${c('País da nacionalidade',employee.nacionalidade||'BRASIL')}${c('Estado civil',employee.estado_civil)}</div>
 <h2>FILIAÇÃO</h2><div class="grid">${c('Pai',employee.pai)}${c('Mãe',employee.mae)}</div>
 <table><tr><th>Cédula de Identidade</th><th>Data de emissão</th><th>Órgão/UF emissor</th><th>Título Eleitoral</th><th>Zona</th><th>Seção</th></tr><tr><td>${esc(employee.rg||'')}</td><td>${dateBR(employee.rg_emissao)}</td><td>${esc(employee.rg_orgao||'')}</td><td>${esc(employee.titulo_eleitor||'')}</td><td>${esc(employee.titulo_eleitor_zona||'')}</td><td>${esc(employee.titulo_eleitor_secao||'')}</td></tr></table>
 <table><tr><th>CTPS</th><th>Série</th><th>Data expedição CTPS</th><th>UF CTPS</th><th>CPF</th><th>CNH</th><th>Categoria</th></tr><tr><td>${esc(employee.ctps||'')}</td><td>${esc(employee.ctps_serie||'')}</td><td>${dateBR(employee.ctps_expedicao)}</td><td>${esc(employee.ctps_uf||'')}</td><td>${esc(employee.cpf||'')}</td><td>${esc(employee.cnh||'')}</td><td>${esc(employee.cnh_categoria||'')}</td></tr></table>
 <table><tr><th>Doc. militar</th><th>Categoria</th><th>Cor</th><th>Sexo</th><th>Grau de instrução</th><th>Deficiência</th><th>Telefone</th></tr><tr><td>${esc(employee.certificado_reservista||'')}</td><td>${esc(employee.reservista_categoria||'')}</td><td>${esc(employee.cor||'')}</td><td>${esc(employee.sexo||'')}</td><td>${esc(employee.escolaridade||'')}</td><td>${esc(employee.deficiencia||'')}</td><td>${esc(employee.telefone||'')}</td></tr></table>
 <table><tr><th>Cargo</th><th>Função</th><th>C.B.O.</th></tr><tr><td>${esc(employee.cargo_nome||'')}</td><td>${esc(employee.cargo_nome||'')}</td><td>${esc(cbo)}</td></tr></table>
 <table><tr><th>Data de Admissão</th><th>Salário</th><th>Por</th><th>Horário de Trabalho</th><th>Horário de Intervalo</th></tr><tr><td>${dateBR(employee.admissao)}</td><td>${money(employee.salario_centavos)}</td><td>Mês</td><td>das ${time(employee.jornada_inicio,'07:00')} às ${time(employee.jornada_fim,'17:00')}</td><td>das ${time(employee.intervalo_inicio,'11:00')} às ${time(employee.intervalo_fim,'12:00')}</td></tr></table>
 <table><tr><th colspan="4">FGTS</th></tr><tr><th>Optante</th><th>Opção em</th><th>Conta vinculada no banco</th><th>Data da Retificação</th></tr><tr><td>${Number(employee.fgts_optante)!==0?'Sim':'Não'}</td><td>${dateBR(employee.fgts_opcao_em)}</td><td>${esc(employee.conta_bancaria||'')}</td><td></td></tr></table>
 <table><tr><th colspan="4">PROGRAMA DE INTEGRAÇÃO SOCIAL - PIS</th></tr><tr><th>Cadastrado em</th><th>Sob nº</th><th>Domicílio bancário</th><th>Nº banco / Agência / End. agência</th></tr><tr><td></td><td>${esc(employee.pis||'')}</td><td>${esc(employee.banco||'')}</td><td>${esc([employee.banco,employee.agencia].filter(Boolean).join(' / '))}</td></tr></table>
 <h2>ALTERAÇÕES DE SALÁRIO, CARGO E/OU FUNÇÃO</h2><div class="box blank"></div>
 <table><tr><th>FÉRIAS - PERÍODO AQUISITIVO</th><th>FÉRIAS - PERÍODO DE GOZO</th><th>FÉRIAS - PERÍODO ABONO PECUNIÁRIO</th><th>Obs.: advertências, suspensões, transferências etc.</th></tr><tr><td class="blank"></td><td></td><td></td><td></td></tr></table>
 <table><tr><th>ACIDENTES DE TRABALHO, DOENÇAS OU DOENÇAS PROFISSIONAIS</th><th>RESCISÃO DE CONTRATO DE TRABALHO</th></tr><tr><td class="blank"></td><td>Data da saída:<br><br>Tipo do desligamento:</td></tr></table>
 <table><tr><th>CONTRIBUIÇÃO SINDICAL</th><th>ASSINATURAS</th></tr><tr><td class="blank"></td><td class="center">____________________________<br>${esc(employee.nome||'')}<br><br>____________________________<br>${esc(employer)}</td></tr></table><h2>OBSERVAÇÕES</h2><div class="box blank"></div>`
 return page('REGISTRO DE EMPREGADO',body,'.grid{grid-template-columns:1fr 1fr 1fr}.cell{min-height:25px}body{font-size:7.8pt}table{font-size:7.4pt}.blank{height:54px}')
}
module.exports={registrationTemplate}
