const { esc,dateBR,companyName,page } = require('./common.cjs')
const li=(items)=>`<ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`
function serviceOrderTemplate({employee,company,work}){
 const employer=companyName(company)
 const body=`<div class="box"><b>Data:</b> ${dateBR(employee.admissao)}<br><b>OBRA:</b> ${esc(work?.nome||'')}<br><b>EMPRESA:</b> ${esc(employer)}<br><b>NOME DO FUNCIONÁRIO:</b> ${esc(employee.nome)}<br><b>CPF:</b> ${esc(employee.cpf||'')} &nbsp;&nbsp; <b>FUNÇÃO:</b> ${esc(employee.cargo_nome||'')}</div>
 <p>Pela presente Ordem de Serviço, objetivamos informar os trabalhadores sobre as condições de segurança e saúde às quais estão expostos e os procedimentos preventivos e de utilização de Equipamentos de Proteção Individual.</p>
 <h2>1 - ATIVIDADES DESENVOLVIDAS</h2>${li(['Transporte de materiais e equipamentos utilizados na execução dos serviços','Seleção de materiais e equipamentos adequados aos serviços','Abertura de valetas e rasgos em alvenaria para redes hidráulicas','Marcação de tubulações, passagens e furos em alvenarias, lajes e pisos','Corte, roscamento, curvatura e união de tubos','Posicionamento e fixação de tubos em alvenarias e estruturas','Teste hidrostático em tubulações','Instalação de louças sanitárias, esgoto, caixas d’água, chuveiros e metais','Instalação de prumadas de gás combustível quando aplicável','Reparo e manutenção em instalações hidráulicas'])}
 <h2>2 - RISCOS DE OPERAÇÃO</h2><p><b>Físicos:</b> Ruído. <b>Químicos:</b> Poeiras minerais e substâncias químicas diversas. <b>Biológicos:</b> Não aplicável. <b>Ergonômicos:</b> Transporte manual de cargas. <b>Acidentes:</b> Queda de altura, queda no mesmo nível, queda de objetos, cortes, perfurações, escoriações, ferramentas inadequadas ou defeituosas, máquinas e equipamentos.</p>
 <h2>3 - EQUIPAMENTOS DE PROTEÇÃO INDIVIDUAL (EPI)</h2>${li(['Capacete para proteção contra impactos','Vestimenta adequada: calça e camisa','Calçado de segurança contra agentes cortantes e perfurantes','Calçado apropriado em locais com umidade','Luvas contra agentes abrasivos e escoriantes','Luvas para agentes químicos quando aplicável','Protetor auditivo em locais com ruído','Óculos contra impactos de partículas','Respirador semifacial filtrante contra poeiras e névoas'])}
 <h2>4 - MEDIDAS PREVENTIVAS</h2>${li(['Verificar níveis de ruído e utilizar proteção auditiva','Verificar poeiras e substâncias químicas e utilizar proteção respiratória/luvas','Treinamento ergonômico para transporte manual de cargas','Instalar e respeitar guarda-corpo, linha de vida, fechamentos e sinalização','Isolar áreas com risco de queda de objetos','Utilizar capacete, vestimentas, calçados e luvas adequados','Analisar continuamente ferramentas, máquinas e equipamentos','Realizar manutenção preventiva de máquinas e equipamentos'])}
 <h2>5 - ORIENTAÇÕES DE SEGURANÇA DO TRABALHO</h2>${li(['Paralisar o serviço ao constatar irregularidade de segurança e comunicar o supervisor','Não executar atividade para a qual não esteja treinado, autorizado ou habilitado','Não transitar na obra sem capacete e calçado de segurança','Não remover ou ultrapassar proteções existentes','Usar EPIs apenas para a finalidade a que se destinam e conservá-los','Verificar ferramentas manuais e elétricas antes do uso','Não improvisar extensões nem reparar equipamento elétrico defeituoso','Não fabricar ou utilizar andaimes inadequados','Seguir recomendações ergonômicas para levantamento e transporte de cargas'])}
 <h2>6 - TREINAMENTOS NECESSÁRIOS</h2>${li(['NR-33 quando houver trabalho em espaço confinado','NR-35 quando houver trabalho em altura'])}
 <h2>7 - PROCEDIMENTO EM CASO DE ACIDENTES</h2>${li(['Comunicar imediatamente o supervisor','Verificar o estado e a gravidade do acidentado','Desobstruir o acesso do resgate, isolar a área e afastar pessoas','Informar ao resgate apenas informações verdadeiras','Não tocar ou mover o acidentado salvo extrema necessidade','Não realizar primeiros socorros sem treinamento adequado'])}
 <h2>8 - TERMO DE RESPONSABILIDADE</h2><p>Declaro que fui plenamente orientado quanto aos procedimentos de segurança do trabalho presentes neste documento, recebi uma cópia, estou ciente dos riscos da atividade e das medidas disciplinares aplicáveis ao descumprimento desta Ordem de Serviço.</p><p class="center">Ribeirão Preto, ${dateBR(employee.admissao)}</p><div class="sig"><div>ASS. FUNCIONÁRIO<br>${esc(employee.nome)}</div><div>ASS. RESPONSÁVEL</div></div>`
 return page('ORDEM DE SERVIÇO — SEGURANÇA E SAÚDE DO TRABALHO',body,'ul{margin:2px 0 5px 18px;padding:0}li{margin:1px 0}body{font-size:8.3pt}')
}
module.exports={serviceOrderTemplate}
