import {describe,expect,it} from 'vitest';
import {clearDiagnosticDraft,type DiagnosticDraftRecord,type DiagnosticDraftStore,diagnosticDraftTable,readDiagnosticDraft,saveDiagnosticDraft,type StoredDiagnosticDraftRecord} from '../backend/diagnostic-draft-store';
import type {DiagnosticDraft} from '../backend/diagnostic-draft';
class MemoryDraftStore implements DiagnosticDraftStore{private rows=new Map<string,StoredDiagnosticDraftRecord[]>();private sequence=0;async list(table:string){return[...(this.rows.get(table)||[])]}async add(table:string,record:DiagnosticDraftRecord){const row={...record,id:`draft-${++this.sequence}`};this.rows.set(table,[...(this.rows.get(table)||[]),row])}async update(table:string,id:string,record:DiagnosticDraftRecord){this.rows.set(table,(this.rows.get(table)||[]).map(row=>row.id===id?{...record,id}:row))}async delete(table:string,id:string){this.rows.set(table,(this.rows.get(table)||[]).filter(row=>row.id!==id))}}
const legacy=(skillIndex:number,level:number):DiagnosticDraft=>({version:1,skillIndex,level,assigned:{leitura:'level:N2'},updatedAt:'2026-08-26T12:00:00.000Z'});
const current=(questionIndex:number):DiagnosticDraft=>{const ids=['diag-com-01','diag-com-02','diag-com-03'];const responses=Object.fromEntries(ids.slice(0,questionIndex).map(id=>[id,'resposta']));return{version:2,questionIndex,responses,confirmationIds:[],updatedAt:'2026-08-27T12:00:00.000Z'}};
describe('persistência do rascunho da sondagem',()=>{
  it('mantém compatibilidade com rascunhos V1 enquanto o novo fluxo usa V2',async()=>{const store=new MemoryDraftStore();await saveDiagnosticDraft(store,'participant-1',legacy(2,3));const saved=await readDiagnosticDraft(store,'participant-1');expect(saved?.version).toBe(1);if(saved?.version===1){expect(saved.skillIndex).toBe(2);expect(saved.level).toBe(3)}});
  it('salva, lê e atualiza o mesmo rascunho V2 sem duplicar registros',async()=>{const store=new MemoryDraftStore();await saveDiagnosticDraft(store,'participant-1',current(2));await saveDiagnosticDraft(store,'participant-1',current(3));const saved=await readDiagnosticDraft(store,'participant-1');expect(saved?.version).toBe(2);if(saved?.version===2)expect(saved.questionIndex).toBe(3);expect((await store.list(diagnosticDraftTable('participant-1')))).toHaveLength(1)});
  it('isola o rascunho por participante',async()=>{const store=new MemoryDraftStore();await saveDiagnosticDraft(store,'participant-1',current(1));await saveDiagnosticDraft(store,'participant-2',current(2));const one=await readDiagnosticDraft(store,'participant-1'),two=await readDiagnosticDraft(store,'participant-2');if(one?.version===2)expect(one.questionIndex).toBe(1);if(two?.version===2)expect(two.questionIndex).toBe(2)});
  it('limpa somente o rascunho solicitado',async()=>{const store=new MemoryDraftStore();await saveDiagnosticDraft(store,'participant-1',current(1));await saveDiagnosticDraft(store,'participant-2',current(2));expect(await clearDiagnosticDraft(store,'participant-1')).toBe(true);expect(await clearDiagnosticDraft(store,'participant-1')).toBe(false);expect(await readDiagnosticDraft(store,'participant-1')).toBeNull();expect(await readDiagnosticDraft(store,'participant-2')).not.toBeNull()});
});
