import { db, json, error, requireAuth, withScopes, requireAdminEmailAllowlist } from '@appdeploy/sdk';
import { setEducationParticipantStatusByEmail } from './education';
import { writePlatformAudit } from './platform-audit';

export type PlatformSystem='gestao'|'obra360'|'universidade'|'finance';
export type PlatformSystemGrant={enabled:boolean;role:string};
export type PlatformAccess={id?:string;email:string;name?:string;platformRole:'superadmin'|'user';status:'pending'|'active'|'blocked';employeeId?:string;companyIds:string[];projectIds:string[];systems:Record<PlatformSystem,PlatformSystemGrant>;provisionalCode?:string;claimedBy?:string;sessionVersion:number;revokedAt?:string;createdAt:string;updatedAt:string};
const SUPERADMIN_EMAIL='nutricionistaalmeidavh@gmail.com';
const ADMIN_EMAILS=[SUPERADMIN_EMAIL];
const SYSTEMS:PlatformSystem[]=['gestao','obra360','universidade','finance'];
const ROLES:Record<PlatformSystem,string[]>={gestao:['admin','consulta'],obra360:['admin','encarregado','funcionario'],universidade:['superadmin','admin','rh','gestor','colaborador'],finance:['superadmin','admin','financeiro','consulta']};
const now=()=>new Date().toISOString();
const norm=(v:unknown)=>String(v||'').trim().toLowerCase();
const safe=(v:string)=>v.replace(/[^a-zA-Z0-9_-]/g,'_');
function hashKey(v:string){let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
const emailTable=(email:string)=>'platform_access_email_'+hashKey(norm(email));
const codeTable=(code:string)=>'platform_access_code_'+safe(code.toUpperCase());
const auditTable='platform_access_audit';
const rec=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const arr=(v:unknown)=>Array.isArray(v)?v.map(String).filter(Boolean):[];
const unique=(v:string[])=>Array.from(new Set(v));
const newCode=()=>crypto.randomUUID().replace(/-/g,'').slice(0,8).toUpperCase();
const emptySystems=():Record<PlatformSystem,PlatformSystemGrant>=>({gestao:{enabled:false,role:'consulta'},obra360:{enabled:false,role:'funcionario'},universidade:{enabled:false,role:'colaborador'},finance:{enabled:false,role:'consulta'}});
function normalizeSystems(value:unknown,base?:Record<PlatformSystem,PlatformSystemGrant>){const raw=rec(value),out=base?structuredClone(base):emptySystems();for(const key of SYSTEMS){const item=rec(raw[key]);if(Object.prototype.hasOwnProperty.call(item,'enabled'))out[key].enabled=item.enabled===true;const role=String(item.role||out[key].role);if(ROLES[key].includes(role))out[key].role=role}return out}
function superSystems():Record<PlatformSystem,PlatformSystemGrant>{return{gestao:{enabled:true,role:'admin'},obra360:{enabled:true,role:'admin'},universidade:{enabled:true,role:'superadmin'},finance:{enabled:true,role:'superadmin'}}}
function legacySystems(role:string,modules:string[],isSuperadmin:boolean){if(isSuperadmin)return superSystems();const out=emptySystems();if(role==='admin'){out.gestao={enabled:true,role:'admin'};out.universidade={enabled:true,role:'admin'};if(modules.includes('finance'))out.finance={enabled:true,role:'admin'}}else out.universidade={enabled:true,role:'colaborador'};if(modules.includes('obra360'))out.obra360={enabled:true,role:role==='foreman'?'encarregado':role==='employee'?'funcionario':'admin'};return out}
async function indexEmail(id:string,email:string){const table=emailTable(email),items=(await db.list<Record<string,unknown>>(table,{limit:1})).items;if(items[0])await db.update(table,[{id:items[0].id,record:{accessId:id}}]);else await db.add(table,[{accessId:id}])}
async function indexCode(id:string,code:string){const table=codeTable(code),items=(await db.list<Record<string,unknown>>(table,{limit:1})).items;if(items[0])await db.update(table,[{id:items[0].id,record:{accessId:id}}]);else await db.add(table,[{accessId:id}])}
export async function getPlatformAccess(email:string){const refs=(await db.list<Record<string,unknown>>(emailTable(email),{limit:1})).items,ref=refs[0];if(!ref)return null;const id=String(ref.accessId||''),[item]=await db.get<PlatformAccess>('platform_accesses',[id]);return item?{...item,id}:null}
export async function getPlatformAccessById(id:string){const[item]=await db.get<PlatformAccess>('platform_accesses',[id]);return item?{...item,id}:null}
async function saveAccess(access:PlatformAccess){if(!access.id)throw new Error('Acesso sem ID.');const{id,...record}=access;await db.update('platform_accesses',[{id,record:record as unknown as Record<string,unknown>}]);await indexEmail(id,access.email);if(access.provisionalCode)await indexCode(id,access.provisionalCode);return access}
async function addAccess(record:Omit<PlatformAccess,'id'>){const[id]=await db.add('platform_accesses',[record as unknown as Record<string,unknown>]);if(!id)throw new Error('Não foi possível criar o acesso.');await indexEmail(id,record.email);if(record.provisionalCode)await indexCode(id,record.provisionalCode);return{...record,id}}
async function audit(actor:{userId:string;email?:string},action:string,target?:PlatformAccess,details?:Record<string,unknown>){await db.add(auditTable,[{actorUserId:actor.userId,actorEmail:actor.email,action,targetId:target?.id,targetEmail:target?.email,at:now(),details:details||{}}]);await writePlatformAudit({action:'ACCESS_'+action.toUpperCase(),actorUserId:actor.userId,actorEmail:actor.email,companyId:target?.companyIds?.[0],projectId:target?.projectIds?.[0],entity:'platform_access',entityId:target?.id,source:'platform-access',metadata:{targetEmail:target?.email,...(details||{})}})}
export function platformAccessView(a:PlatformAccess){return{id:a.id,email:a.email,name:a.name||null,platformRole:a.platformRole,status:a.status,employeeId:a.employeeId||null,companyIds:a.companyIds||[],projectIds:a.projectIds||[],systems:a.systems,sessionVersion:a.sessionVersion||0,revokedAt:a.revokedAt||null}}
export function platformSystemRole(a:PlatformAccess|null,key:PlatformSystem){return a?.systems?.[key]?.enabled?a.systems[key].role:''}
export async function ensurePlatformAccessForMember(input:{email:string;name?:string;companyId:string;projectId:string;employeeId?:string;role:string;modules:string[];isSuperadmin?:boolean}){const email=norm(input.email),isSuperadmin=input.isSuperadmin===true||email===SUPERADMIN_EMAIL;let current=await getPlatformAccess(email);if(current){let changed=false,next={...current};if(isSuperadmin&&(current.platformRole!=='superadmin'||current.status!=='active')){next={...next,platformRole:'superadmin',status:'active',systems:superSystems(),revokedAt:undefined};changed=true}const companyIds=unique([...(next.companyIds||[]),input.companyId]),projectIds=unique([...(next.projectIds||[]),input.projectId]);if(companyIds.length!==next.companyIds.length||projectIds.length!==next.projectIds.length){next={...next,companyIds,projectIds};changed=true}if(input.employeeId&&!next.employeeId){next={...next,employeeId:input.employeeId};changed=true}if(input.name&&next.name!==input.name){next={...next,name:input.name};changed=true}if(changed){next.updatedAt=now();current=await saveAccess(next)}return current}const stamp=now();return addAccess({email,name:input.name,platformRole:isSuperadmin?'superadmin':'user',status:'active',employeeId:input.employeeId,companyIds:[input.companyId],projectIds:[input.projectId],systems:legacySystems(input.role,input.modules,isSuperadmin),sessionVersion:0,createdAt:stamp,updatedAt:stamp})}
async function ensureSuperadmin(user:{userId:string;email?:string;name?:string}){let current=await getPlatformAccess(SUPERADMIN_EMAIL);if(current){if(current.platformRole!=='superadmin'||current.status!=='active'){current={...current,platformRole:'superadmin',status:'active',systems:superSystems(),revokedAt:undefined,updatedAt:now()};await saveAccess(current)}return current}const stamp=now();return addAccess({email:SUPERADMIN_EMAIL,name:user.name,platformRole:'superadmin',status:'active',companyIds:[],projectIds:[],systems:superSystems(),sessionVersion:0,claimedBy:user.userId,createdAt:stamp,updatedAt:stamp})}
function parseInput(body:unknown,existing?:PlatformAccess){const b=rec(body),email=existing?.email||norm(b.email),name=String(b.name||existing?.name||'').trim()||undefined,employeeId=String(b.employeeId||existing?.employeeId||'').trim()||undefined,companyIds=unique(arr(Object.prototype.hasOwnProperty.call(b,'companyIds')?b.companyIds:existing?.companyIds)),projectIds=unique(arr(Object.prototype.hasOwnProperty.call(b,'projectIds')?b.projectIds:existing?.projectIds)),systems=normalizeSystems(Object.prototype.hasOwnProperty.call(b,'systems')?b.systems:existing?.systems,existing?.systems);return{email,name,employeeId,companyIds,projectIds,systems}}
const secured=[requireAuth(),withScopes('email','profile')] as const;
const adminSecured=[requireAuth(),withScopes('email','profile'),requireAdminEmailAllowlist(ADMIN_EMAILS)] as const;
export const PLATFORM_ACCESS_ROUTES={
'GET /api/platform/me':[...secured,async c=>{const email=norm(c.user!.email);let access=email===SUPERADMIN_EMAIL?await ensureSuperadmin(c.user!):await getPlatformAccess(email);if(!access)return error('Seu acesso ainda não foi configurado.',403);return json({access:platformAccessView(access)})}],
'POST /api/platform/claim':[...secured,async c=>{const b=rec(c.body),code=String(b.code||'').trim().toUpperCase();if(!/^[A-Z0-9]{8}$/.test(code))return error('Credencial provisória inválida.',400);const refs=(await db.list<Record<string,unknown>>(codeTable(code),{limit:1})).items,ref=refs[0];if(!ref)return error('Credencial provisória inválida ou expirada.',404);const access=await getPlatformAccessById(String(ref.accessId||''));if(!access||access.provisionalCode!==code)return error('Credencial provisória inválida.',404);if(norm(access.email)!==norm(c.user!.email))return error('Esta credencial pertence a outro e-mail.',403);if(access.status==='blocked')return error('Este acesso está bloqueado.',403);const next={...access,status:'active' as const,claimedBy:c.user!.userId,provisionalCode:undefined,updatedAt:now()};await saveAccess(next);await db.delete(codeTable(code),[ref.id]);await audit(c.user!,'credential_claimed',next);return json({access:platformAccessView(next)})}],
'GET /api/platform/system/:system':[...secured,async c=>{const key=String(c.params.system) as PlatformSystem;if(!SYSTEMS.includes(key))return error('Sistema inválido.',400);const email=norm(c.user!.email),access=email===SUPERADMIN_EMAIL?await ensureSuperadmin(c.user!):await getPlatformAccess(email);const allowed=!!access&&access.status==='active'&&access.systems[key]?.enabled===true;return json({allowed,role:allowed?access!.systems[key].role:null,access:access?platformAccessView(access):null},allowed?200:403)}],
'GET /api/platform/catalog':[...adminSecured,async()=>{const companies=(await db.list<Record<string,unknown>>('companies',{limit:100})).items,projects=(await db.list<Record<string,unknown>>('projects',{limit:100})).items;const enriched=[] as Record<string,unknown>[];for(const p of projects.slice(0,50)){const projectId=p.id,meta=(await db.list<Record<string,unknown>>('project_meta_'+safe(projectId),{limit:1})).items[0],state=rec(meta?.state),employees=(Array.isArray(state.employees)?state.employees:[]).map(rec).map(e=>({id:String(e.id||''),name:String(e.name||''),phone:String(e.phone||e.mobile||''),jobRole:String(e.jobRole||e.role||e.function||'')})).filter(e=>e.id&&e.name);enriched.push({id:projectId,companyId:String(p.companyId||''),name:String(p.name||''),customer:String(p.customer||''),employees})}return json({companies:companies.map(c=>({id:c.id,name:String(c.name||'Empresa')})),projects:enriched,systems:SYSTEMS,roles:ROLES})}],
'GET /api/platform/accesses':[...adminSecured,async()=>{const items=(await db.list<PlatformAccess>('platform_accesses',{limit:200})).items;return json({accesses:items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).map(a=>({...platformAccessView(a as PlatformAccess&{id:string}),provisionalCode:a.provisionalCode||null,claimedBy:a.claimedBy||null}))})}],
'POST /api/platform/accesses':[...adminSecured,async c=>{const input=parseInput(c.body);if(!/^\S+@\S+\.\S+$/.test(input.email))return error('E-mail inválido.',400);if(await getPlatformAccess(input.email))return error('Já existe um acesso para este e-mail.',409);const stamp=now(),code=newCode(),access=await addAccess({...input,platformRole:input.email===SUPERADMIN_EMAIL?'superadmin':'user',status:input.email===SUPERADMIN_EMAIL?'active':'pending',provisionalCode:input.email===SUPERADMIN_EMAIL?undefined:code,sessionVersion:0,createdAt:stamp,updatedAt:stamp});await audit(c.user!,'access_created',access,{systems:access.systems,companyIds:access.companyIds,projectIds:access.projectIds});return json({access:{...platformAccessView(access),provisionalCode:access.provisionalCode||null}},201)}],
'PUT /api/platform/accesses/:id':[...adminSecured,async c=>{const current=await getPlatformAccessById(c.params.id);if(!current)return error('Acesso não encontrado.',404);if(current.platformRole==='superadmin'&&norm(current.email)===SUPERADMIN_EMAIL){const input=parseInput(c.body,current),next={...current,...input,status:'active' as const,systems:superSystems(),platformRole:'superadmin' as const,updatedAt:now()};await saveAccess(next);await audit(c.user!,'superadmin_access_updated',next);return json({access:platformAccessView(next)})}const input=parseInput(c.body,current),next={...current,...input,updatedAt:now()};await saveAccess(next);await audit(c.user!,'access_updated',next,{systems:next.systems,companyIds:next.companyIds,projectIds:next.projectIds});return json({access:platformAccessView(next)})}],
'POST /api/platform/accesses/:id/block':[...adminSecured,async c=>{const current=await getPlatformAccessById(c.params.id);if(!current)return error('Acesso não encontrado.',404);if(current.platformRole==='superadmin')return error('O Superadmin principal não pode ser bloqueado.',409);const blocked=rec(c.body).blocked===true,next={...current,status:(blocked?'blocked':'active') as 'blocked'|'active',sessionVersion:(current.sessionVersion||0)+1,revokedAt:blocked?now():undefined,updatedAt:now()};await saveAccess(next);await setEducationParticipantStatusByEmail(next.email,!blocked);await audit(c.user!,blocked?'access_blocked':'access_unblocked',next,{sessionVersion:next.sessionVersion});return json({access:platformAccessView(next)})}],
'POST /api/platform/accesses/:id/credential':[...adminSecured,async c=>{const current=await getPlatformAccessById(c.params.id);if(!current)return error('Acesso não encontrado.',404);if(current.platformRole==='superadmin')return error('Superadmin não usa credencial provisória.',409);const code=newCode(),next={...current,provisionalCode:code,status:'pending' as const,claimedBy:undefined,sessionVersion:(current.sessionVersion||0)+1,updatedAt:now()};await saveAccess(next);await indexCode(next.id!,code);await audit(c.user!,'credential_regenerated',next);return json({code,access:platformAccessView(next)})}],
'GET /api/platform/audit':[...adminSecured,async()=>{const items=(await db.list<Record<string,unknown>>(auditTable,{limit:100})).items;return json({audit:items.sort((a,b)=>String(b.at||'').localeCompare(String(a.at||''))).slice(0,50)})}]
};
