import { describe, expect, it } from 'vitest'
import { renderMhAdmissionTemplate } from './mh-admission-templates.cjs'

const employee:any={nome:'TESTE FUNCIONARIO',cpf:'000.000.000-00',rg:'11.111.111-1',rg_orgao:'SSP/SP',ctps:'12345',ctps_serie:'0001',ctps_uf:'SP',pis:'123.45678.90-1',data_nascimento:'2000-01-02',naturalidade:'RIBEIRÃO PRETO-SP',nacionalidade:'BRASIL',estado_civil:'SOLTEIRO',pai:'PAI TESTE',mae:'MAE TESTE',cargo_nome:'ENCANADOR',cbo:'724110',admissao:'2026-09-01',salario_centavos:266475,matricula_esocial:'0050600013',jornada_inicio:'07:00',intervalo_inicio:'11:00',intervalo_fim:'12:00',jornada_fim:'17:00',experiencia_dias:45,experiencia_fim:'2026-10-15',vale_transporte_opcao:1,endereco_logradouro:'Rua Teste',endereco_numero:'100',endereco_bairro:'Centro',endereco_cidade:'Ribeirão Preto',endereco_uf:'SP',cep:'14000-000',fgts_optante:1,fgts_opcao_em:'2026-09-01'}
const company:any={razao_social:'MH HIDRAULICA RP LTDA',cnpj:'50.733.669/0001-60',endereco:'Rua Shirlei Chirieleison Lane, 100 APTO 104'}

describe('official MH admission templates',()=>{
 it('renders the two-page experience contract structure',()=>{const html=renderMhAdmissionTemplate('contrato_experiencia',employee,company);expect(html).toContain('CONTRATO DE TRABALHO A TÍTULO DE EXPERIÊNCIA');expect(html).toContain('PRORROGAÇÃO DO CONTRATO');expect(html).toContain('artigos 479 e 480');expect(html).toContain('TESTE FUNCIONARIO')})
 it('renders only the canonical registration form',()=>{const html=renderMhAdmissionTemplate('ficha_registro',employee,company);expect(html).toContain('REGISTRO DE EMPREGADO');expect(html).toContain('Matrícula eSocial');expect(html).toContain('ALTERAÇÕES DE SALÁRIO');expect(html).toContain('RESCISÃO DE CONTRATO')})
 it('renders the complete safety service-order sections',()=>{const html=renderMhAdmissionTemplate('ordem_servico',employee,company,[],{nome:'OBRA TESTE'});for(const section of ['ATIVIDADES DESENVOLVIDAS','RISCOS DE OPERAÇÃO','EQUIPAMENTOS DE PROTEÇÃO','MEDIDAS PREVENTIVAS','ORIENTAÇÕES DE SEGURANÇA','TREINAMENTOS NECESSÁRIOS','PROCEDIMENTO EM CASO DE ACIDENTES','TERMO DE RESPONSABILIDADE'])expect(html).toContain(section)})
 it('renders twelve transit route rows and fingerprint area',()=>{const html=renderMhAdmissionTemplate('vale_transporte',employee,company);expect((html.match(/RESIDÊNCIA\/TRABALHO/g)||[]).length).toBe(6);expect((html.match(/TRABALHO\/RESIDÊNCIA/g)||[]).length).toBe(6);expect(html).toContain('Impressão Digital')})
 it('renders EPI responsibilities and real default kit',()=>{const html=renderMhAdmissionTemplate('ficha_epi',employee,company);expect(html).toContain('FICHA DE CONTROLE DE E.P.I.');expect(html).toContain('Capacete c/ jugular');expect(html).toContain('36099');expect(html).toContain('Máscara PFF2');expect(html).toContain('10578')})
 it('renders union opposition addressed to Ribeirão Preto union',()=>{const html=renderMhAdmissionTemplate('carta_sindical',employee,company);expect(html).toContain('Sindicato da Construção Civil de Ribeirão Preto');expect(html).toContain('CONTRIBUIÇÃO ASSISTENCIAL / CONTRIBUIÇÃO CONFEDERATIVA')})
})
